#!/bin/bash

java -cp .:/usr/local/lib/antlr-4.13.2-complete.jar:/usr/local/webots/lib/controller/java/Controller.jar \
  -Djava.library.path=/usr/local/webots/lib/controller/java/ \
  AdapterController
