#!/bin/bash

# Este script compila todo el proyecto
# Para ejecutarlo, hay que estar situado en el directorio raíz del proyecto
# Los ficheros compilados .class se guardan en el directorio bin


echo "🔨 Compilando proyecto Robolang..."


# Establever el class path a las librerías 
export CP="lib/*"

# Compilar
javac -cp "$CP" \
    -d bin \
    src/main/*.java src/lenguaje/*.java src/interpretes/*.java \
    src/sound/*.java src/webots/*.java src/stddraw/*.java src/consola/*.java

# Comprobar errores de compilación
if [ $? -eq 0 ]; then
    echo "✅ Compilación exitosa"
else
    echo "❌ Errores de compilación"
fi



