#!/bin/bash

javac -cp .:lib/Controller.jar:lib/antlr-4.13.2-complete.jar \
    lenguaje/*.java robolang_webots/controllers/robolang_webots_controller/*.java \
    robolang_stddraw/*.java main/*.java

