#!/bin/bash

javac -cp .:lib/Controller.jar:lib/antlr-4.13.2-complete.jar \
    main/*.java lenguaje/*.java interpretes/*.java \
    robolang_webots/*.java robolang_stddraw/*.java robolang_consola/*.java 

