#!/bin/bash

# Este script permite ejecutar el interprete de consola interpretes.InterpreteConsola.java
# El InterpreteConsola.java ejecuta código fuente robolang con el robolang_consola.RobotConsola

java -cp "bin:lib/antlr-4.13.2-complete.jar" interpretes.InterpreteConsola
