#!/bin/bash

# Menu principal - Lanzador interactivo Robolang
# Muestra menú con intérpretes disponibles

# Colores
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Path librerías dinámicas
export LD_LIBRARY_PATH=lib:$LD_LIBRARY_PATH

# Classpath completo
CP="bin:lib/*"

 
 # Lanzar Menú
 echo "⚙️ Menú de selección de controlador:"
 java -cp "$CP" \
     -Djava.library.path=lib \
     main.Menu

echo -e "${GREEN}🏠 Simulación Webots ${NC}"





